version: "3.9"

services:
  virtual_telescope_master:
    build: ./virtual_telescope_master
    networks:
      - telescope
  state_api:
    build: ./state_api
    networks:
      - telescope
  webcam:
    build: ./webcam
    networks:
      - telescope
    ports:
      - 5001:5000
  lab_master:
    build: ./lab_master
    networks:
      - telescope
  website:
    build: ./website
    networks:
      - telescope
    ports:
      - 5000:5000


networks:
  telescope:
    driver: bridge
